"""Every indicator must reproduce TA-Lib's output exactly (within float noise).

The reference fixture is generated by ``tests/golden/generate_indicator_references.py``
from real TA-Lib; see that script for regeneration instructions.
"""

import json
from pathlib import Path

import pytest

from tradebot.indicators import Adx, Atr, Ema, Rsi

REFERENCES = json.loads(
    (Path(__file__).parent.parent / "golden" / "indicator_references.json").read_text()
)
PERIODS = [2, 14, 50]
RELATIVE_TOLERANCE = 1e-9


def assert_matches_reference(actual: list[float | None], expected: list[float | None]) -> None:
    assert len(actual) == len(expected)
    for index, (ours, talib_value) in enumerate(zip(actual, expected, strict=True)):
        if talib_value is None:
            assert ours is None, f"index {index}: expected warm-up None, got {ours}"
        else:
            assert ours == pytest.approx(talib_value, rel=RELATIVE_TOLERANCE), f"index {index}"


@pytest.mark.parametrize("period", PERIODS)
def test_ema_matches_talib(period: int) -> None:
    ema = Ema(period)
    actual = [ema.update(close) for close in REFERENCES["close"]]
    assert_matches_reference(actual, REFERENCES["ema"][str(period)])


@pytest.mark.parametrize("period", PERIODS)
def test_rsi_matches_talib(period: int) -> None:
    rsi = Rsi(period)
    actual = [rsi.update(close) for close in REFERENCES["close"]]
    assert_matches_reference(actual, REFERENCES["rsi"][str(period)])


@pytest.mark.parametrize("period", PERIODS)
def test_adx_matches_talib(period: int) -> None:
    adx = Adx(period)
    actual = [
        adx.update(high, low, close)
        for high, low, close in zip(
            REFERENCES["high"], REFERENCES["low"], REFERENCES["close"], strict=True
        )
    ]
    assert_matches_reference(actual, REFERENCES["adx"][str(period)])


@pytest.mark.parametrize("period", PERIODS)
def test_atr_matches_talib(period: int) -> None:
    atr = Atr(period)
    actual = [
        atr.update(high, low, close)
        for high, low, close in zip(
            REFERENCES["high"], REFERENCES["low"], REFERENCES["close"], strict=True
        )
    ]
    assert_matches_reference(actual, REFERENCES["atr"][str(period)])
